### ISSUE TITLE
How to deal with GC (Allocation Failure)

### ISSUE THREAD

**Issue by atais** [scalameter/scalameter#168]
Hello,

I am analyzing the performance of some Java structures. The test I am working on can be found on my repo, fe: [MapBenchmark.scala](https://github.com/atais/Performance-Tests/blob/master/src/test/scala/pl/msiatkowski/MapBenchmark.scala)

The problem I am facing is that I am trying to create a map of 100.000 to 1.000.000 elements. In my opinion it should not take much memory (but maybe my calculations are wrong, `8 bytes (object) * 1.000.000 = ~ 8MB?`), still I am facing a rather strange issue:

```
[GC (Allocation Failure)  713753K->83145K(2064896K), 0,1452724 secs]
GC detected.
```
(similar message is displayed 100000 times)

which horribly slows down my benchmark. I have no idea why the GC is fired so often and why it takes so long. What am I doing wrong? 
Thanks a lot!

**Comment by tiborlotz** [comment]
Hi,

From what I can see from a glance, it is very likely that you are instantiating each of your hash maps inside the DSL block (`performance of`) and then reusing the same map many times in the same snippet. You should instead generate the value using a [**generator**](http://scalameter.github.io/home/gettingstarted/0.7/generators/index.html). If the value is mutated by the snippet, you should use a `setUp` or `tearDown` block to restore the generated object to the original state.

For example, I found this to be the proper way to write a collection benchmark:

https://github.com/scalameter/scalameter/blob/master/src/test/scala/org/scalameter/collections/MapBenchmarks.scala

Example of the `tearDown` method (thing that gets run after every snippet, but does not get measured):

https://github.com/scalameter/scalameter/blob/master/src/test/scala/org/scalameter/collections/MapBenchmarks.scala#L202

If this is not the problem, then it's a good idea to start VisualVM, dump the heap state, and see which objects are being allocated a lot.

Btw, a couple of comments:

- Using generators instead of instantiating state inside a scope is the proper way to run ScalaMeter tests. You should map an `Int` generator to a generator of hash maps, for example.
- The way you're structuring your test right now might incur additional overheads. Since you picked `Int` for the input type and the output type of the lambda passed to `testSingle`, *probably* you will not get boxing, but if you picked e.g. `Int => String`, the integers would definitely be boxed.  In general, it's a good idea to avoid abstraction and factoring out common functionality in tests and benchmarks, as it becomes more clear what is being tested/benchmarked. The link above is a good example of how to write tests with the fewest amount of allocations for various `Range` objects, lambdas, etc.

**Comment by atais** [comment]
Hello, thanks for a broad answer.

I have tried to follow the pattern but again faced some issue.

The code I try to run is really simple:

```
val hashMapS: String = "HashMap"

def sizes: Gen[Int] = Gen.range("size")(size, 10 * size, 3 * size)
def emptyMap: Gen[util.HashMap[Int, Int]] = Gen.single(hashMapS)(new util.HashMap[Int, Int]())

def empty = Gen.crossProduct(sizes, emptyMap)

performance of "Different Map implementations" config opts in {
  measure method "add" in {
    using(empty) curve hashMapS in { case (r, map) =>
      (0 until r).map(i => {
        val r = map.put(i, i)
        r
      })
    }
  }
}
```
Source (I will not probably keep it forever: [here](https://github.com/atais/Performance-Tests/blob/master/src/test/scala/pl/msiatkowski/MapBenchmarkError.scala)

Anyway I get a compilation error:
```
Error:(26, 68) No Pickler available for java.util.HashMap[Int,Int]. 
Please import org.scalameter.picklers.Implicits for existing ones,
or define your own,
or import org.scalameter.picklers.noPickler._ and use SerializationPersistor.
  def emptyMap: Gen[util.HashMap[Int, Int]] = Gen.single("hashmap")(new util.HashMap[Int, Int]())
```

The way  I could get around this was to import `import org.scalameter.picklers.noPickler._`

But I do not understand what I have just done. What is `Pickler` for?
Are Java collections not supported?

Thanks!

**Comment by tiborlotz** [comment]
I think you should import `noPickler`:

http://scalameter.github.io/home/gettingstarted/0.7/persistors/index.html

You only need picklers if you use JSON-based persistors.

About your benchmark, you are assuming that every call to the snippet instantiates a new instance of the hash map. That is not the case. Values from the generators are reused across measurements. The reason for this is that *generally* it could be slow and costly to regenerate the instance between calls to the snippet. You should *really* use `tearDown` as I explained above.

**Comment by atais** [comment]
I understand. The test I send was just quickly fixed after reading your advices and I have bumped into another problem (with Pickler) which I wanted to clarify. 

Now, as I understand in 'setUp' and 'tearDown' you can modify the state of the object passed to the 'in' section I have yet another question.

Both those functions should modify the state of the object, so why can they return a value? And can it be accessed.

Thanks so much for a deep clarification!

**Comment by tiborlotz** [comment]
I think it's for convenience only, so that you can pass an existing function with an arbitrary return type (same reason why Scala collection `foreach` returns `U`). As far as I can tell:

https://github.com/scalameter/scalameter/blob/master/scalameter-core/src/main/scala/org/scalameter/Measurer.scala#L128

The return value is ignored.

**Comment by axel22** [comment]
Thanks, @tiborlotz , your answer pretty much nails it. I guess I can close this issue.
