### ISSUE TITLE
OnlineHtmlReport does not consider differences in units

### ISSUE THREAD

**Issue by zegerhoogeboom** [scalameter/scalameter#184]
Currently the `OnlineHtmlReport` does not consider differences in units. The Y axis always shows:

> running time [ms]

This is even though there is the `units` key available in the test results (or - at least in the JSON version). For example, with a measurer of `override def measurer = new Executor.Measurer.MemoryFootprint` the label should say `memory usage [kb]`.

**Comment by axel22** [comment]
Due to low amount of time, I'm keeping ScalaMeter mostly in maintenance mode. But I went ahead and fixed this, you will now get the correct unit.

https://github.com/scalameter/scalameter/issues/184

There is no "memory usage" concept, since this does not exist in the ScalaMeter's data model. If you want that label too, I suggest that you maybe send in a patch.

**Comment by zegerhoogeboom** [comment]
Great! And good to know, I'll keep it in mind and perhaps you'll see more PR's from me although I'm also low on available time.
