### ISSUE TITLE
upgrade jackson-module-scala?

### ISSUE THREAD

**Issue by SethTisue** [scalameter/scalameter#205]
over at https://github.com/scala/community-builds/pull/785 we're upgrading the Scala community build to use jackson-module-scala 2.9.6, which is the latest version at https://github.com/FasterXML/jackson-module-scala/releases

upgrading scalameter from 2.8.5 to 2.9.6 causes test failures; at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3458/console we see e.g.

```
[scalameter:error] com.fasterxml.jackson.databind.JsonMappingException: Failed to specialize base type scala.collection.immutable.Map<org.scalameter.Parameter<java.lang.Object>,java.lang.Object> as scala.collection.immutable.ListMap$Node, problem: Type parameter #1/2 differs; can not specialize org.scalameter.Parameter<java.lang.Object> with java.lang.Object (through reference chain: org.scalameter.History["results"]->scala.collection.convert.Wrappers$IterableWrapper[0]->org.scalameter.CurveData["measurements"]->scala.collection.convert.Wrappers$IterableWrapper[0]->org.scalameter.Parameters["axisData"])
```

why, I don't know. the same thing happens if I bump the dependency in a checkout of this repo, without dbuild involvement.

it's not critical that scalameter remain in the community build, but we would _like_ to keep it, and in order to keep it, this upgrade is required

**Comment by axel22** [comment]
Ok - I will soon push the update. Should I also release a new version?

**Comment by SethTisue** [comment]
no release needed, we build everything from source

**Comment by axel22** [comment]
It looks like the semantics of what Jackson is willing to serialize automatically and what it is not slightly changed between the version, with Jackson trying to be smart about what is an allowed type parameter of a class. Ah, these semantic versioning ideologies... as if anything other than SHA1 could ever be relied on to work correctly ;)

Anyway, I changed one place in the code that is now constructing an `immutable.Map` instead of a `ListMap`, so the error went away. Running `test` on Scala 2.11 with Jackson `2.9.6` works locally for me, so I suppose other versions should work as well.

**Comment by axel22** [comment]
I am closing for now since I think this should be fixed, feel free to reopen otherwise.

**Comment by SethTisue** [comment]
Thanks! I'll try it (maybe not this week) and let you know if I run into any problems.
