### ISSUE TITLE
is it possible to measure and report in nanoTime instead of millseconds?

### ISSUE THREAD

**Issue by notyy** [scalameter/scalameter#94]
when measuring two method whose performances have very big difference, the small one(close to 1ms) can't been viewed clearly.

**Comment by axel22** [comment]
No, there is currently no `nanoTime` method. In my experience, nanos
were to inaccurate for measurements.
But if you really need it, you can create a custom Measurer that uses
nanoTime to output time in millis

See:

https://github.com/scalameter/scalameter/blob/master/scalameter-core/src/main/scala/org/scalameter/Measurer.scala

There are several measurer implementations here, feel free to take the
one you need and tweak it.
If you have something that turns out to measure nanos well, feel free
to submit a pull request.
